server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: admin

#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.code.mybatis.bean
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true