server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ssm
    username: root
    password: admin

mybatis:
  type-aliases-package: com.code.sbmdemo.bean
  not-empty: false
  identity: MYSQL